---
- name: Install NGINX on server
  hosts: webservers
  become: true
  gather_facts: true
  vars:
    listen_port: 8080

  tasks:

    - name: Install epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install NGINX from epel-repository
      yum: 
        name: nginx
        state: present

    - name: Start NGINX
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Copy custom NGINX configuration file
      template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0600'
        owner: root
        group: root
      register: nginx_config_copy

    - name: Check nginx config for errors
      shell: nginx -t
      register: nginx_config_check
      failed_when: "'FAILED' in nginx_config_check.stderr"

    - name: Debug rc from nginx -t
      debug:
        var: nginx_config_check.rc

    - name: See an error if exist
      debug:
        var:  nginx_config_check.stderr_lines
      when: nginx_config_check.rc == 1

    - name: Reload NGINX
      systemd:
        name: nginx
        state: reloaded
      when:
        - nginx_config_check.rc == 0
        - nginx_config_copy.changed == true

    - name: Check if ngix started
      uri:
        url: "http://127.0.0.1:8080"
        method: GET
      register: curl_result
      until: curl_result.status == 200
      retries: 10
      delay: 5
    

    - name: Print that nothing to reload
      debug:
        msg:
          - "!!!! Nothing to reload - no new configuration  !!!!"
      when:
        - curl_result.status == 200
        - nginx_config_copy.changed == false
    
    - name: Print RELOAD message
      debug:
        msg:
          - "########################################"
          - "     NGIX was successfully reload "
          - "########################################"
      when:
        - curl_result.status == 200
        - nginx_config_copy.changed == true